language: node_js

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      node_js: '6'
    - os: osx
      node_js: '6'

script:
- npm test

env:
  global:
  - secure: TXCnp5nMm7o0vlL8f+0nMIEui3ObFKDL8igCzhMcvsdXOeHfdPpfD4vZvGL3SGMirnyJsdYLkU11VOfkIBknWv6Em7XDSBQAw/edBfsmv+qYvepEXkBAd7DqGBlfKoF42wD7BQemRxc2ZQ6Pd4Us8CwouVYJjjHAPiJT+4UMtTVaq09BVFUh3qcSp81UZHMnswctuZq7OrBJWLHPZIQHE8LIchx1kp+VEYckpXEikxfKzTmDuwNPH094CfVtIBOSIhZo1XechSlhpFusiCafcc2bIUqbd0UzjA+26eKXHF2ppWS5qAzVGl6a2iX6dE5hLu+2GeAvkXdOFMw9ozYALERV2cmY+fw2RrOB08JqgiVFjKWauL9hsgTq2AlF0M5QPVB18B2zYz+JRm/B+lRHzNbnokHM7K6CQTQ80MpIrijD83FLCrxkdnL9hisI+SxWCNOUgonoETsmJ94f7Dd/BPYHI4vJVfz/ub5V7eQPIvlIVavJ5QJDauYtgzHvDCgCAN4SdqqEQgYW9F0Xhemnm8aSpfYFOAw+zKd4tAjutErVfSQFk3VdwvDeEboIk5dXyopOSqtKZVcdIQ5aSKyqcN5Y9gXvk7Pfq/VIL+zjkcN+rpmkTnROfU39PRzP9SwsIw8FdTfs5N4HCeOKvwfXebEwMPRdtssVKMlUnQ+J6us=

after_success:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run buildLinux; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export FILE_TO_UPLOAD=$(ls dist/tanetroamer-desktop-*-x86_64.tar.xz); fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run buildOSX; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export FILE_TO_UPLOAD=$(ls dist/tanetroamer-desktop-*-x86_64.dmg); fi
- ls -alh

addons:
  apt:
    packages:
    - xvfb

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x24" ; fi

install:
- npm install npm -g
- npm install electron-builder@next -g
- npm install
- build --version

after_failure:
- cat npm-debug.log

#deploy:
#  provider: releases
#  api_key:
#    secure: qiMQ9QLZabf7nWuP1nHTlrMSOLUw/cdBVtVei+9NMltVOQmDf58YFY4yT9sUT5L90aATb6bgBGDhae/dN035Wruo0dZm1kQXvC+0eCMr51IJ5ctTUAHTAu646nFSDUUIcB0Fy8nVYDIX4v+ol2swJz/bwRECFOcaqH2dumsuFjv2GkLBzG1ObexMGn1SJyZG4p3425HWkFv1ng+2IAMWCDWtfQjVLMd/bN+aMlE2L+C4T++dwErurroNn7PCOM9wiGt9xYFkL3QT9SIcz8EsWfe2tRsAsOSK+QBMfqYh8lWDcAALgW17VGgUs+2Jmdu4BmmFXwiiiWIG05EwlsNoKPTTU5jOeX56m/508Wp3FYWUxAzlgFkEnwrsFMNuD1wD2p+XcoZIieikCqmlrQUZinUCeVkDYIVaJeerR093MsT+ThX4hvMC1HF6Y8rNut1lY2zcOFgiHK67PGbjwtW2ucLe8/N01Q5dwQF1dVZSc7V9mnOuFO+Qk16vxryaXNNvtOYmlFMLRxhXbb+EPzFcfBtgM8wkztksWhEKQ73UCq45Pj/bMmr5Y8J4AQ1LKOmmjibyr7MVbpZU0zuwN1BK3ipVu67uUxUyk1KoYSrfx2r2df/Ioe4AW/By9v2rqDiWSFnMlAJ3BUWvw5o4waUPTRQu14OcfDzZKP/RUUaRcR8=
#  file:
#    - "${FILE_TO_UPLOAD}"
#  skip_cleanup: true
#  on:
#    branch: master
#    repo: ALiangLiang/TANetRoamer-desktop
#    tags: true
